name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/html/words-boardgame/
            git pull origin main
            git status
            npm install
            npm run build

      - name: Get App Version
        run: echo "APP_VERSION=$(cat package.json | jq -r .version)" >> $GITHUB_ENV

      - name: Get Latest Commit Message
        id: get_commit_message
        run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Send SMS Notification
        run: |
          curl "https://my.zitasms.com/services/send.php?key=${{ secrets.ZITASMS_KEY }}&number=%2B359876841230&message=WordsGame%20Deployed.%20Version:%20${{ env.APP_VERSION }}.%20Commit:%20${{ env.COMMIT_MESSAGE }}&devices=2108&type=sms&prioritize=0"
